In [85]:
import pandas as pd # Import the pandas library that helps you work with data in tables and give it the alias 'pd'

In [87]:
df = pd.read_csv("insurance.csv") # Read the CSV file named "insurance.csv" into a dataframe called 'df'

In [89]:
df

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [91]:
df = pd.get_dummies(df).astype(int) #Convert categorical 'smoker' and 'Sex' column to one-hot encoding column and  drop the first category

In [93]:
df

      age  bmi  children  charges  sex_female  sex_male  smoker_no  smoker_yes
0      19   27         0    16884           1         0          0           1
1      18   33         1     1725           0         1          1           0
2      28   33         3     4449           0         1          1           0
3      33   22         0    21984           0         1          1           0
4      32   28         0     3866           0         1          1           0
...   ...  ...       ...      ...         ...       ...        ...         ...
1333   50   30         3    10600           0         1          1           0
1334   18   31         0     2205           1         0          1           0
1335   18   36         0     1629           1         0          1           0
1336   21   25         0     2007           1         0          1           0
1337   61   29         0    29141           1         0          0           1

[1338 rows x 8 columns]

In [95]:
df.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes'],
      dtype='object')

In [97]:
df = pd.get_dummies(df, drop_first=True).astype(int) #Convert categorical 'smoker' column to one-hot encoding column and  drop the first category

In [99]:
df

      age  bmi  children  charges  sex_female  sex_male  smoker_no  smoker_yes
0      19   27         0    16884           1         0          0           1
1      18   33         1     1725           0         1          1           0
2      28   33         3     4449           0         1          1           0
3      33   22         0    21984           0         1          1           0
4      32   28         0     3866           0         1          1           0
...   ...  ...       ...      ...         ...       ...        ...         ...
1333   50   30         3    10600           0         1          1           0
1334   18   31         0     2205           1         0          1           0
1335   18   36         0     1629           1         0          1           0
1336   21   25         0     2007           1         0          1           0
1337   61   29         0    29141           1         0          0           1

[1338 rows x 8 columns]

In [101]:
inp = df[['age', 'bmi', 'children',
       'charges', 'sex_male','smoker_yes']] # Assign the input variable columns to the variable named  'inp'

In [103]:
inp # Show the output

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [105]:
op = df[["charges"]]## Assign the output  'Profit' column to the variable named  'op'

In [107]:
op

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [109]:
from sklearn.model_selection import train_test_split #Import the train_test_split function from the sklearn.model_selection module
x_train,x_test,y_train,y_test=train_test_split(inp, op, test_size=0.30, random_state=0) #Split data into 70% train and 30% test

In [111]:
from sklearn.linear_model import LinearRegression # import the LinearRegression class from sklearn module
regressor = LinearRegression() # Create an instance of the LinearRegression model
regressor.fit(x_train,y_train) # Train the model using the training data

LinearRegression()

In [113]:
weight=regressor.coef_ # Get the coefficients
weight # Display the weights

array([[ 2.68847315e-13, -4.23109684e-13,  7.81326298e-13,
         1.00000000e+00, -4.52683174e-13, -5.32793468e-14]])

In [115]:
bias = regressor.intercept_ #Get the intercept
bias # Show the bias

array([1.45519152e-11])

In [117]:
y_pred=regressor.predict(x_test) # Predict the target values using the test data

In [119]:
from sklearn.metrics import r2_score # Import the r2_score function from sklearn.metrics
r_score = r2_score(y_test, y_pred)  # Calculate the R-squared value
r_score  # Show the R-squared score

1.0

In [121]:
import pickle # Import the pickle module for saving and loading models
filename ="final_model_multilinear.sav"  # Name of the file to save the model
pickle.dump(regressor, open(filename,'wb')) # Save the model to the file
loaded_regressor = pickle.load(open("final_model_multilinear.sav","rb"))  # Load the model from the file

In [173]:
result = loaded_regressor.predict([[1315,115816,297114,1,0]])  # Make a prediction for input values by entering the values in  all the input columns
result  # Show the prediction result

D:\Anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[56618.99238948]])